# Generated by Django 4.2.7 on 2023-12-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
